# This is the configuration used to check the rubocop source code.
AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - 'app/views/**/*'
    - 'bin/*'
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'log/**/*'
    - 'node_modules/**/*'
    - 'public/**/*'
    - 'scripts/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'test/**/*'
    - '.git/**/*'
    - 'config/initializers/devise.rb'
    - 'spec/spec_helper.rb'
    - 'spec/rails_helper.rb'
    - 'spec/controller_helpers.rb'

Metrics/LineLength:
  Max: 130

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'config/**/*'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/DateTime:
  Enabled: false

Style/MixinUsage:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
   Max: 20
